### ISSUE TITLE
Improve default featured image on block grid item

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#226]
The default image on block-grid-item is currently using holder.js as a fallback default – needs changing to the proper default image, when complete.

**Comment by simonpmiles** [comment]
@juliotaylor Could you link me to or send me the higher def versions of these logos please?

**Comment by juliotaylor** [comment]
this is all I have. use the light grey one, on a white background.

**Comment by simonpmiles** [comment]
Duplicato
