### ISSUE TITLE
Implement shortcode parmaters for ordering

### ISSUE THREAD

**Issue by jrgmartin** [bigspring/monolith#254]
I have added a new orderby parameter to the child pages shortcode.  This means you you can now use:

```[childpages orderby="menu_order"]```

It will always default to post_title. 

The editor buttons need to be amended to include the new order options - they should match the important ones available to WP_Query as follows:

- [ ] title
- [ ] date
- [ ] rand
- [ ] menu_order

**Comment by juliotaylor** [comment]
seems to be like the default ordering should be page order, not title.

also, has this already been done? I don't see any commits

**Comment by jrgmartin** [comment]
That's easy to change. Page title seemed most sensible to me as it requires
no user input to work in a sensible way. Let me know your preference

I definitely committed to the 2.0 branch yesterday. Is that where you
checked?

On Wednesday, January 7, 2015, Julio Taylor <notifications@github.com>
wrote:

> seems to be like the default ordering should be page order, not title.
>
> also, has this already been done? I don't see any commits
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bigspring/monolith/issues/254#issuecomment-69002732>.
>


-- 

Jon Martin
BigSpring Web Development
Office: +44 (0) 115 906 1321
Mobile: + 44 (0) 7787 121897
Skype: jon.bigspring
http://www.bigspring.co.uk
http://www.twitter.com/bigspringweb
http://www.facebook.com/bigspringweb

BigSpring is a trading division of Big Spring (UK) Ltd
Registered in England & Wales No. 06741331, 29 St Austins Drive,
Nottingham, NG4 3EY

**Comment by juliotaylor** [comment]
page order is what we've always used as default, no?

I am referring to the commit on this issue. Also the milestones is 2.1 but the commit is on 2.0? it's quite confusing.

**Comment by jrgmartin** [comment]
Ah OK - this issue is some follow up work related to the commit I made, rather than being for the work I committed.

I've changed the default order to menu_order.
