### ISSUE TITLE
Enable WP_DEBUG in dev mode by default?

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#265]

**Comment by juliotaylor** [comment]
@jrgmartin any thoughts on this yet?

**Comment by dmseaton** [comment]
Maybe we should add some kind of toggle switch to the admin bar so this can be changed quickly?

Following links look useful:

http://wordpress.stackexchange.com/questions/47123/how-to-define-wp-debug-as-true-outside-of-wp-config-php
http://www.wordpressluv.com/how-to-easily-enabledisable-debug-mode-in-wordpress/
http://php.net/manual/en/function.runkit-constant-redefine.php

**Comment by jrgmartin** [comment]
I think we should leave it on permanently when in development mode to avoid it being forgotten. 



Jon Martin

BigSpring Web Development

Office: +44 (0) 115 906 1321

Mobile: + 44 (0) 7787 121897

Skype: jon.bigspring

http://www.bigspring.co.uk

http://www.twitter.com/bigspringweb

http://www.facebook.com/bigspringweb




BigSpring is a trading division of Big Spring (UK) Ltd

Registered in England & Wales No. 06741331, 29 St Austins Drive, Nottingham, NG4 3EY
