### ISSUE TITLE
Create styled list shortcode

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#284]
Shortcode to render styled lists as per utility css clases (tick, chevron, etc)

**Comment by simonpmiles** [comment]
ADD TO MCE-BUTTON.JS
				//List Shortcode
				{
					text: 'List',
					onclick: function() {
						editor.windowManager.open( {
							title: 'Insert list style',
							body: [
								{
									type: 'listbox',
									name: 'listboxListTypes',
									label: 'List Type',
									'values': [
										{text: 'Chevrons', value: 'chevron'}	,									
										{text: 'Caret List', value: 'caret'},											
										{text: 'Tick List', value: 'tick'}											
									]
								},
							],
							onsubmit: function( e ) {
								editor.insertContent( '[list type="' + e.data.listboxListTypes + '" ][/list]');
							}
						});
					}
				}, // end list shortcode

ADD TO INC/SHORTCODES

/**
 * Renders wrapper div to create different types of lists
 * @param array $atts
 * @param string $content
 * @return string
 */
function list_shortcode( $atts, $content = null ) {
	extract( shortcode_atts( array(
			'type' => '', /* no-bullet, ticks, chevron etc */
	), $atts ) );


	$output = '<div class="monolith-list '. $type . '">';
	$output .= apply_filters('the_content', $content);
	$output .= '</div>';

	return $output;
}
add_shortcode('list', 'list_shortcode');
