### ISSUE TITLE
Refactor site options

### ISSUE THREAD

**Issue by juliotaylor** [bigspring/monolith#288]
The existing site options should be repurposed to be used as "Contact Information" only.

It should retain all existing fields, but lose the ones related to the blog / news (we'll decide how that works later).

It should also have a new field for the contact form selection, which will power the new CTA block detailed in #283

**Comment by simonpmiles** [comment]
@juliotaylor  I've partially done this but have not removed the blog section or created the CTA block heresy.

**Comment by juliotaylor** [comment]
fixed in #301
