### ISSUE TITLE
Replace instances of == with ===

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#292]
Generally speaking, using `===` to mark equivalence (e.g. `if ($num === 30)`) is better practice than using `==` as the latter attempts to figure out what you mean and makes assumptions that can be troublesome and bug-prone. The former type is stricter and encourages better error handling.

I say this because I happened across an example of `==` or `!=` being used and a quick search revealed more. This applies to PHP _and_ Javascript!

**Comment by jrgmartin** [comment]
Good call!

**Comment by dmseaton** [comment]
Hooray

**Comment by jrgmartin** [comment]
I have partially fixed this.  There are still instances within shortcodes.php that need to be fixed.
