### ISSUE TITLE
Git ignore compiled assets altogether?

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#293]
My rationale here is similar to the issue I raised about bower dependencies - essentially there's no particular benefit to having `base.css` and the gang fired off with each commit, potentially confusing git - why not just let Grunt do its thing on all sides?

**Comment by jrgmartin** [comment]
We need this for when we deploy the file to the live server.  So rather than have to manage it manually, I think we should keep it in place.  Unless I'm missing something?

**Comment by dmseaton** [comment]
Haha, no, I am the one who's missing something. Disregard.
