### ISSUE TITLE
Post object inaccessible in content loop

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#294]
I noticed an issue [here](https://github.com/bigspring/monolith/blob/3965e88851a2936f579a8ec83c4fd99c3a79e869/layouts/organisms/content.php#L13) when trying to conditionally display the date based on `$post->post_type` - the $post variable isn't available. I'd have just used functional equivalents but `$post->ID` is already utilised on the page and results in an incomplete `<article>` block ID property.

We need to decide whether to use `global $post` in the builder/block or `get_the_ID()` in the article ID property.

**Comment by juliotaylor** [comment]
this seems like an urgent issue?

**Comment by dmseaton** [comment]
I reckon we should just use get_the_ID() in place of `$post->ID`, as the global post object isn't otherwise declared.

**Comment by jrgmartin** [comment]
I fixed this by making the ```$post``` variable available
