### ISSUE TITLE
Show excerpt by default

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#295]
Encountered this issue whilst setting up a project today. Needs to be investigated as it may have been a result of a botched theme directory rename, but the steps to follow are as follows:

1. Install/activate monolith
2. Add new user
3. Login as new user and check post/page - excerpts should be visible (and positioned below the title field, if memory serves).

**Comment by juliotaylor** [comment]
iirc we removed the position component of this

**Comment by dmseaton** [comment]
One less thing to worry about! They should still be appearing for new users by default though.
