### ISSUE TITLE
FontAwesome dependencies not deployed as bower_components is ignored

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#297]
I propose that we resolve this by:

- override the FontAwesome relative path in an appropriate SCSS file if possible
- extend Grunt to copy required files to site assets

In order to maintain best practices for dependencies we should keep bower_components in .gitignore

**Comment by juliotaylor** [comment]
temporarily removed bower_components from ignore file until this is fixed in a better way

**Comment by dmseaton** [comment]
Just FYI, I successfully implemented a fix for this in Just Landlords - it's just an amendment to the FA path in compiler.scss, and Grunt copies the FA font files to populate the new path. Will need some examples of fairheadwebicons in use so I can do similar with that (assuming they're still going to be used).

**Comment by juliotaylor** [comment]
that's fine, happy for you to fix permantently on dev

**Comment by dmseaton** [comment]
Fixed, needs review for Fairweather stuff but fa appears to work
