### ISSUE TITLE
Test Fairhead icons

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#298]
See whether they work on dev branch?

Run `munch -b develop` to download the dev branch. Latest munch version recommended.

**Comment by juliotaylor** [comment]
these are used for the social media icons, so if those work then this is fine. Do you still need me to test it?

**Comment by juliotaylor** [comment]
these icons no longer work

**Comment by juliotaylor** [comment]
also, it hasn't copied anything into assets/fonts
