### ISSUE TITLE
Update .gitignore

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#337]
Add uploads folder

**Comment by jrgmartin** [comment]
I don't think this should be done as part of the Monolith gitignore as it's relevant to a Wordpress root directory, so it'd be better as part of Munch.

**Comment by juliotaylor** [comment]
i agree. it wouldn't work anyway as the ignore file would be too deep in the directory.

@dmseaton can you undo this?

**Comment by dmseaton** [comment]
Done. Should now include only relevant exclusions.
