### ISSUE TITLE
Builder path/class name issue

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#373]
The first argument passed to the builder is used to locate the layout path of the organism - for this reason it's often convenient to pass a path to the class (e.g. _frontpage/block-grid_ where a custom bg to be used on the frontpage is found at _organisms/frontpage/block-grid.php_).

However, the layout path is also used directly in class names, prepended with _builder-_. This means that any time a path like _frontpage/block-grid_ is passed to the builder, the organism markup will include an element with a badly-formed markup:

`<div class="builder builder-frontpage/block-grid">`

WP's sanitize_title() function might be suitable for resolving this cleanly.

**Comment by jrgmartin** [comment]
sanitize_title() sounds like a good plan.  Happy for you to hotfix as this seems like a quick but important one to avoid invalid markup.
