### ISSUE TITLE
Snippet featured images

### ISSUE THREAD

**Issue by dmseaton** [bigspring/monolith#376]
@juliotaylor @jrgmartin

See [this line](https://github.com/bigspring/monolith/blob/9eba963aa199655e57840f8d31abd2e38b53709a/layouts/molecules/snippet.php#L39) - having a check for _has_post_thumbnail_ makes `the_monolith_post_thumbnail()` completely pointless (as the purpose of that function is to provide a fallback image when there is no post thumbnail).

I'd recommend we remove the _has_post_thumbnail_ check personally, as a fallback image is usually useful.

**Comment by juliotaylor** [comment]
agree, but the wrapping markup is quite important. can it be put into the function instead? or better still, can the thumbnail function use a molecule for layout?

cc @harrybigspring

**Comment by dmseaton** [comment]
The function is for utility and so should do one discrete task well, in this case returning image tag markup - adding wrapping markup to its output makes assumptions that restrict where it can be used.

The wrapping markup doesn't need to be removed - the _has_image_ Builder argument handles whether or not an image needs to be shown.

**Comment by juliotaylor** [comment]
but without the check, the wrapping markup would remain should the image not load

**Comment by dmseaton** [comment]
The image will always load, because if there's no thumbnail the fallback image (in assets/img/) will be used instead.

**Comment by juliotaylor** [comment]
OK FINE. GOSH.

**Comment by dmseaton** [comment]
VICTORY
